/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
/usr/bin/python3.7 /home/dam/Dokumenty/Labs/TS/Lista2/Zad1.py >> out
